// <auto-generated />
using System;
using Duende.Bff.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Web.BFF.Database.Migrations.Sessions
{
    [DbContext(typeof(SessionDbContext))]
    [Migration("20260820173925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sessions")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Duende.Bff.EntityFramework.UserSessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("partition_key");

                    b.Property<DateTime>("Renewed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewed");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_id");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("Expires")
                        .HasDatabaseName("ix_user_sessions_expires");

                    b.HasIndex("PartitionKey", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_partition_key_key");

                    b.HasIndex("PartitionKey", "SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_partition_key_session_id");

                    b.HasIndex("PartitionKey", "SubjectId", "SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_partition_key_subject_id_session_id");

                    b.ToTable("user_sessions", "sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
