<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>e42b6a00-f395-4a61-abab-1d72dfd65840</UserSecretsId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Clients\Web.BFF\Web.BFF.csproj" />
    <ProjectReference Include="..\..\Services\Identity.API\Identity.API.csproj" />
  </ItemGroup>

</Project>
